<template>
  <div class="phone-lock-view page-container">
    <!-- 毛玻璃背景光斑 -->
    <div class="aurora" aria-hidden="true">
      <span class="blob blob-1"></span>
      <span class="blob blob-2"></span>
      <span class="blob blob-3"></span>
      <span class="blob blob-4"></span>
    </div>

    <div class="stage">
      <!-- ==================== iPhone ==================== -->
      <div class="phone-frame">
        <span class="side-btn side-silent"></span>
        <span class="side-btn side-vol-up"></span>
        <span class="side-btn side-vol-down"></span>
        <span class="side-btn side-power"></span>

        <div class="phone-bezel">
        <div class="phone-screen">
          <!-- 墙纸 -->
          <div
            class="wallpaper"
            :class="[`wp-${wallpaper}`, { 'wallpaper-home': phase === 'unlocked' }]"
          ></div>

          <!-- 屏幕玻璃反光 -->
          <div class="screen-glare" aria-hidden="true"></div>

          <!-- 输错时的柔和光晕（不闪、不晃） -->
          <div class="error-glow" :class="{ 'is-on': errorFlash }" aria-hidden="true"></div>

          <!-- 灵动岛 -->
          <div class="dynamic-island"></div>

          <!-- 状态栏 -->
          <div class="status-bar">
            <span class="status-time">{{ clockTime }}</span>
            <div class="status-icons">
              <!-- 信号 -->
              <svg class="status-icon" viewBox="0 0 18 12" aria-hidden="true">
                <rect x="0" y="8" width="3" height="4" rx="1" fill="currentColor" />
                <rect x="5" y="6" width="3" height="6" rx="1" fill="currentColor" />
                <rect x="10" y="3" width="3" height="9" rx="1" fill="currentColor" />
                <rect x="15" y="0" width="3" height="12" rx="1" fill="currentColor" />
              </svg>
              <!-- Wi-Fi -->
              <svg class="status-icon" viewBox="0 0 16 12" aria-hidden="true">
                <path
                  d="M8 10.5 5.6 8a3.6 3.6 0 0 1 4.8 0L8 10.5Zm-4.2-4.4a7.4 7.4 0 0 1 8.4 0l1.4-1.5a9.4 9.4 0 0 0-11.2 0l1.4 1.5Z"
                  fill="currentColor"
                />
              </svg>
              <!-- 电量 -->
              <svg class="status-icon status-battery" viewBox="0 0 26 13" aria-hidden="true">
                <rect x="0.5" y="0.5" width="22" height="12" rx="3.5" stroke="currentColor" fill="none" opacity="0.5" />
                <rect x="2" y="2" width="16" height="9" rx="2" fill="currentColor" />
                <path d="M24.5 4.5v4a2.2 2.2 0 0 0 0-4Z" fill="currentColor" opacity="0.5" />
              </svg>
            </div>
          </div>

          <!-- ---------- 1. 设置密码 ---------- -->
          <div v-if="phase === 'setup'" class="screen-body setup-screen">
            <template v-if="setupStep !== 'hint'">
              <div class="setup-head">
                <div class="lock-badge">🔒</div>
                <h2 class="setup-title">{{ setupTitle }}</h2>
                <p class="setup-tip">{{ setupTip }}</p>
                <div class="dots" :class="{ 'is-error': errorFlash, 'is-shaking': shaking }">
                  <span
                    v-for="i in passcodeLength"
                    :key="i"
                    class="dot"
                    :class="{ 'is-filled': draft.length >= i }"
                  ></span>
                </div>
                <p v-if="errorText" class="setup-error">{{ errorText }}</p>
                <div class="segmented">
                  <button
                    v-for="len in PASSCODE_LENGTHS"
                    :key="len"
                    type="button"
                    :class="{ 'is-active': passcodeLength === len }"
                    @click="changePasscodeLength(len)"
                  >
                    {{ len }} 位密码
                  </button>
                </div>
              </div>

              <div class="keypad-panel">
                <PasscodeKeypad
                  :show-delete="draft.length > 0"
                  left-label="🎲"
                  @press="handleDigit"
                  @delete="handleDelete"
                  @left="useRandomPasscode"
                />
              </div>
            </template>

            <div v-else class="hint-step">
              <div class="lock-badge">💡</div>
              <h3 class="hint-title">留个提示给猜的人</h3>
              <p class="hint-sub">（可选，猜的人可以点左下角「提示」查看）</p>
              <input
                v-model="hintText"
                class="hint-input"
                type="text"
                maxlength="20"
                placeholder="比如：我的生日后两位"
              />
              <p v-if="autoGenerated" class="random-tip">
                🎲 已随机生成密码：{{ passcode.split('').join(' ') }}
              </p>
              <button type="button" class="primary-btn" @click="lockPhone">🔒 锁定手机</button>
              <button type="button" class="link-btn" @click="resetGame">重新设置</button>
            </div>
          </div>

          <!-- ---------- 2. 交接 ---------- -->
          <div v-else-if="phase === 'handoff'" class="screen-body handoff-screen">
            <div class="handoff-icon">📱</div>
            <h2 class="handoff-title">手机已锁定</h2>
            <p class="handoff-text">把手机交给要猜密码的人<br />设置的人不许偷看哦 👀</p>
            <div v-if="hintText" class="handoff-hint">💡 提示：{{ hintText }}</div>
            <button type="button" class="primary-btn" @click="startGuessing">开始猜密码</button>
            <button type="button" class="link-btn" @click="resetGame">重新设置密码</button>
          </div>

          <!-- ---------- 3. 锁屏猜密码 ---------- -->
          <div v-else-if="phase === 'locked'" class="screen-body lock-screen">
            <div class="lock-clock">
              <div class="clock-widget">
                <span class="lock-badge">🔒</span>
                <span class="clock-date">{{ clockDate }}</span>
              </div>
              <div class="clock-time">{{ clockTime }}</div>
            </div>

            <div class="lock-prompt">
              <p class="prompt-text">{{ promptText }}</p>
              <div class="dots" :class="{ 'is-error': errorFlash, 'is-shaking': shaking }">
                <span
                  v-for="i in passcodeLength"
                  :key="i"
                  class="dot"
                  :class="{ 'is-filled': draft.length >= i }"
                ></span>
              </div>
              <p v-if="isLockedOut" class="prompt-sub prompt-lockout">
                请在 {{ formatCountdown(lockoutRemaining) }} 后重试
              </p>
              <p v-else-if="errorText" class="prompt-sub">{{ errorText }}</p>
            </div>

            <div class="keypad-panel">
              <PasscodeKeypad
                :disabled="isLockedOut || verifying"
                :show-delete="draft.length > 0"
                :left-label="hintText ? '提示' : ''"
                @press="handleDigit"
                @delete="handleDelete"
                @left="showHint = true"
              />
            </div>
          </div>

          <!-- ---------- 4. 解锁后的桌面 ---------- -->
          <div v-else class="screen-body home-screen">
            <div class="unlock-badge">🎉 解锁成功 · {{ attempts }} 次尝试 · {{ formattedElapsed }}</div>
            <div class="app-grid">
              <div v-for="app in HOME_APPS" :key="app.name" class="app">
                <div class="app-icon" :style="{ background: app.background }">{{ app.icon }}</div>
                <span class="app-name">{{ app.name }}</span>
              </div>
            </div>
            <div class="dock">
              <div v-for="app in DOCK_APPS" :key="app.name" class="app">
                <div class="app-icon" :style="{ background: app.background }">{{ app.icon }}</div>
              </div>
            </div>
          </div>

          <div class="home-indicator"></div>
        </div>
        </div>
      </div>

      <!-- ==================== 侧边信息面板 ==================== -->
      <aside class="info-panel">
        <div class="panel-head">
          <h1 class="panel-title">iPhone 密码锁</h1>
          <span class="phase-chip" :class="`is-${phaseChip.tone}`">{{ phaseChip.label }}</span>
        </div>
        <p class="panel-desc">
          {{
            isChallengeMode
              ? '你正在挑战别人发来的密码，答对才能进桌面。'
              : '设置一个密码锁住手机，然后把密码发给朋友去猜 👀'
          }}
        </p>

        <ol class="rule-list">
          <li>设置 4 位或 6 位密码，锁定手机</li>
          <li>把手机交给朋友，让他 / 她来猜</li>
          <li>连续猜错 {{ ATTEMPTS_BEFORE_LOCKOUT }} 次会被「停用」一段时间</li>
          <li>猜对就能看到手机桌面 🎉</li>
          <li>密码只有设置的人知道，手机不会自动给出任何线索</li>
          <li>电脑上还能直接用键盘敲数字</li>
        </ol>

        <div class="wallpaper-row">
          <span class="wallpaper-label">锁屏墙纸</span>
          <div class="swatches">
            <button
              v-for="item in WALLPAPERS"
              :key="item.id"
              type="button"
              class="swatch"
              :class="{ 'is-active': wallpaper === item.id }"
              :style="{ background: item.preview }"
              :title="item.name"
              :aria-label="`墙纸：${item.name}`"
              @click="wallpaper = item.id"
            ></button>
          </div>
        </div>

          <section v-if="!isChallengeMode && passcode" class="share-card">
            <div class="share-head">
              <span class="share-title">🔗 发给朋友来猜</span>
              <span class="share-badge">哈希校验</span>
            </div>
            <p class="share-desc">
              链接里只有一个单向哈希：密码本身不会出现在链接、地址栏或代码里，也没有任何函数能把答案还原出来，
              对方只能一位一位试。
            </p>
            <el-button
              v-if="shareState !== 'ready'"
              type="primary"
              :loading="shareState === 'generating'"
              @click="generateShareLink"
            >
              {{ shareState === 'generating' ? '生成中…' : '生成挑战链接' }}
            </el-button>
            <template v-else>
              <input
                class="share-input"
                type="text"
                readonly
                :value="shareLink"
                @focus="selectShareInput"
              />
              <div class="share-actions">
                <el-button type="primary" @click="copyShareLink">
                  {{ copied === 'link' ? '已复制 ✓' : '复制链接' }}
                </el-button>
                <el-button @click="copyShareToken">
                  {{ copied === 'token' ? '已复制 ✓' : '复制挑战码' }}
                </el-button>
              </div>
              <ul class="share-facts">
                <li v-if="verifyCostText">
                  本机校验一次约 {{ verifyCostText }}，{{ passcodeLength }} 位密码离线穷举约要
                  {{ bruteForceText }}
                </li>
                <li v-if="passcodeLength === 4" class="is-warn">
                  ⚠️ 4 位只有 1 万种组合，挡不住算力，分享建议用 6 位
                </li>
                <li class="is-muted">
                  客户端只能把作弊成本抬高，挡不住专业算力；真要紧的东西别用这招。
                </li>
              </ul>
            </template>
            <p v-if="shareError" class="share-error">{{ shareError }}</p>
          </section>

          <!-- 猜的人：直接粘贴挑战码也能进 -->
          <section v-if="!isChallengeMode" class="challenge-card">
            <div class="challenge-row">
              <input
                v-model="tokenInput"
                class="challenge-input"
                type="text"
                placeholder="收到挑战码？粘贴进来"
                @keyup.enter="acceptToken"
              />
              <el-button @click="acceptToken">开始挑战</el-button>
            </div>
            <p v-if="tokenError" class="share-error">{{ tokenError }}</p>
          </section>
        <div v-if="phase === 'setup'" class="panel-block">
          <p class="panel-hint">正在手机上设置密码，输入完成后点「锁定手机」。</p>
        </div>

        <template v-else>
          <div class="stats-grid">
            <div class="stat">
              <span class="stat-value">{{ attempts }}</span>
              <span class="stat-label">猜测次数</span>
            </div>
            <div class="stat">
              <span class="stat-value">{{ formattedElapsed }}</span>
              <span class="stat-label">用时</span>
            </div>
            <div class="stat">
              <span class="stat-value">{{ isGuessing ? remainingBeforeLockout : passcodeLength }}</span>
              <span class="stat-label">{{ isGuessing ? '离停用还剩' : '密码位数' }}</span>
            </div>
          </div>

          <div v-if="history.length" class="history">
            <div class="history-title">已经试过的密码</div>
            <div v-for="(item, index) in history" :key="index" class="history-item">
              <span class="history-guess">{{ item.split('').join(' ') }}</span>
              <span class="history-times">第 {{ history.length - index }} 次</span>
            </div>
          </div>

          <div v-if="hintText && phase !== 'handoff'" class="hint-card">💡 对方的提示：{{ hintText }}</div>

          <!-- 设置的人：生成挑战链接发给朋友 -->

          <div class="panel-actions">
            <el-button v-if="phase === 'unlocked'" type="primary" @click="relockSamePasscode">
              再锁一次（同一密码）
            </el-button>
            <el-button @click="resetGame">
              {{ isChallengeMode ? '退出挑战' : '重新设置密码' }}
            </el-button>
          </div>
        </template>
      </aside>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import PasscodeKeypad from '../components/PhoneLock/PasscodeKeypad.vue'
import {
  ATTEMPTS_BEFORE_LOCKOUT,
  PASSCODE_LENGTHS,
  formatCountdown,
  formatDuration,
  formatRoughDuration,
  getLockoutSeconds,
  getRemainingAttemptsBeforeLockout,
  randomPasscode,
  type PasscodeLength
} from '../utils/phone-lock'
import {
  createChallenge,
  encodeChallenge,
  estimateBruteForceSeconds,
  parseChallenge,
  verifyChallenge,
  type Challenge
} from '../utils/phone-lock-challenge'

type Phase = 'setup' | 'handoff' | 'locked' | 'unlocked'
type SetupStep = 'enter' | 'confirm' | 'hint'

const WEEKDAYS = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']

// 锁屏墙纸（preview 用于面板上的色卡）
const WALLPAPERS = [
  { id: 'aurora', name: '极光', preview: 'linear-gradient(140deg, #0b1030, #4b3f9e 45%, #7fd8ff)' },
  { id: 'sunset', name: '日落', preview: 'linear-gradient(140deg, #3a1440, #b8456a 50%, #ffc46b)' },
  { id: 'neon', name: '霓虹', preview: 'linear-gradient(140deg, #180033, #a3167a 50%, #35b6ff)' },
  { id: 'midnight', name: '午夜', preview: 'linear-gradient(140deg, #05070f, #14213c 55%, #3d8fbf)' }
]

const HOME_APPS = [
  { name: '电话', icon: '📞', background: 'linear-gradient(160deg, #4ade80, #16a34a)' },
  { name: '信息', icon: '💬', background: 'linear-gradient(160deg, #60a5fa, #2563eb)' },
  { name: '相机', icon: '📷', background: 'linear-gradient(160deg, #4b5563, #111827)' },
  { name: '照片', icon: '🖼️', background: 'linear-gradient(160deg, #fbbf24, #f97316)' },
  { name: '音乐', icon: '🎵', background: 'linear-gradient(160deg, #fb7185, #e11d48)' },
  { name: '天气', icon: '⛅', background: 'linear-gradient(160deg, #38bdf8, #0284c7)' },
  { name: '日历', icon: '📅', background: 'linear-gradient(160deg, #f8fafc, #cbd5e1)' },
  { name: '设置', icon: '⚙️', background: 'linear-gradient(160deg, #94a3b8, #475569)' }
]

const DOCK_APPS = [
  { name: '电话', icon: '📞', background: 'linear-gradient(160deg, #4ade80, #16a34a)' },
  { name: '浏览器', icon: '🧭', background: 'linear-gradient(160deg, #60a5fa, #1d4ed8)' },
  { name: '信息', icon: '💬', background: 'linear-gradient(160deg, #34d399, #059669)' },
  { name: '音乐', icon: '🎵', background: 'linear-gradient(160deg, #fb7185, #e11d48)' }
]

const phase = ref<Phase>('setup')
const setupStep = ref<SetupStep>('enter')
const passcodeLength = ref<PasscodeLength>(4)
const draft = ref('')
const firstPasscode = ref('')
const passcode = ref('')
const hintText = ref('')
const autoGenerated = ref(false)

const attempts = ref(0)
const failedAttempts = ref(0)
const history = ref<string[]>([])
const elapsed = ref(0)
const lockoutRemaining = ref(0)

const shaking = ref(false)
const errorFlash = ref(false)
const errorText = ref('')
const showHint = ref(false)

const wallpaper = ref('aurora')
const now = ref(new Date())

// 挑战模式：密码不在本地，只有一个只能校验、不能反解的令牌
const challenge = ref<Challenge | null>(null)
const verifying = ref(false)

// 分享面板
const shareToken = ref('')
const shareLink = ref('')
const shareState = ref<'idle' | 'generating' | 'ready'>('idle')
const shareError = ref('')
const copied = ref('')
const tokenInput = ref('')
const tokenError = ref('')
const verifySeconds = ref(0)

let tickTimer: ReturnType<typeof setInterval> | undefined
let shakeTimer: ReturnType<typeof setTimeout> | undefined
let clearTimer: ReturnType<typeof setTimeout> | undefined

const clockTime = computed(() => {
  const h = String(now.value.getHours()).padStart(2, '0')
  const m = String(now.value.getMinutes()).padStart(2, '0')
  return `${h}:${m}`
})

const clockDate = computed(() => {
  const d = now.value
  return `${d.getMonth() + 1}月${d.getDate()}日 ${WEEKDAYS[d.getDay()]}`
})

const formattedElapsed = computed(() => formatDuration(elapsed.value))
const isLockedOut = computed(() => lockoutRemaining.value > 0)
const isGuessing = computed(() => phase.value === 'locked')
const remainingBeforeLockout = computed(() =>
  getRemainingAttemptsBeforeLockout(failedAttempts.value)
)

const isChallengeMode = computed(() => challenge.value !== null)

const phaseChip = computed(() => {
  if (phase.value === 'setup') return { label: '设置密码中', tone: 'setup' }
  if (phase.value === 'unlocked') {
    return isChallengeMode.value
      ? { label: '挑战成功', tone: 'done' }
      : { label: '已解锁', tone: 'done' }
  }
  if (phase.value === 'handoff') return { label: '等待交给朋友', tone: 'wait' }
  if (isLockedOut.value) return { label: 'iPhone 已停用', tone: 'danger' }
  return isChallengeMode.value
    ? { label: '接受挑战中', tone: 'challenge' }
    : { label: '猜密码中', tone: 'run' }
})

// 对方离线穷举大概要多久（用本机实测的单次校验耗时估算）
const bruteForceText = computed(() => {
  if (!verifySeconds.value) return ''
  return formatRoughDuration(estimateBruteForceSeconds(passcodeLength.value, verifySeconds.value))
})

const verifyCostText = computed(() =>
  verifySeconds.value ? `${verifySeconds.value.toFixed(2)} 秒` : ''
)

const promptText = computed(() => {
  if (verifying.value) return '校验中…'
  if (isLockedOut.value) return 'iPhone 已停用'
  return showHint.value && hintText.value ? `💡 ${hintText.value}` : '输入密码'
})

const setupTitle = computed(() => (setupStep.value === 'enter' ? '设置密码' : '请再次输入'))
const setupTip = computed(() =>
  setupStep.value === 'enter' ? '输入完成后会自动进入下一步' : '两次输入需要保持一致'
)

function handleDigit(digit: string) {
  if (phase.value === 'setup') {
    if (setupStep.value === 'hint' || draft.value.length >= passcodeLength.value) return
    errorText.value = ''
    draft.value += digit
    if (draft.value.length === passcodeLength.value) {
      completeSetupEntry()
    }
    return
  }

  if (phase.value === 'locked') {
    if (verifying.value || isLockedOut.value || draft.value.length >= passcodeLength.value) return
    errorText.value = ''
    draft.value += digit
    if (draft.value.length === passcodeLength.value) {
      submitGuess()
    }
  }
}

function handleDelete() {
  if (phase.value === 'setup') {
    if (setupStep.value === 'hint') return
    draft.value = draft.value.slice(0, -1)
    return
  }
  if (phase.value === 'locked' && !isLockedOut.value) {
    draft.value = draft.value.slice(0, -1)
  }
}

function completeSetupEntry() {
  if (setupStep.value === 'enter') {
    firstPasscode.value = draft.value
    draft.value = ''
    setupStep.value = 'confirm'
    return
  }

  if (draft.value === firstPasscode.value) {
    passcode.value = draft.value
    draft.value = ''
    autoGenerated.value = false
    setupStep.value = 'hint'
  } else {
    firstPasscode.value = ''
    draft.value = ''
    setupStep.value = 'enter'
    flashError('两次输入不一致，请重新设置')
  }
}

function changePasscodeLength(length: PasscodeLength) {
  if (passcodeLength.value === length) return
  passcodeLength.value = length
  draft.value = ''
  firstPasscode.value = ''
  setupStep.value = 'enter'
  errorText.value = ''
}

function useRandomPasscode() {
  passcode.value = randomPasscode(passcodeLength.value)
  firstPasscode.value = passcode.value
  draft.value = ''
  autoGenerated.value = true
  setupStep.value = 'hint'
}

function lockPhone() {
  passcodeLength.value = passcode.value.length as PasscodeLength
  resetRound()
  phase.value = 'handoff'
}

function startGuessing() {
  resetRound()
  phase.value = 'locked'
}

function relockSamePasscode() {
  resetRound()
  phase.value = 'handoff'
}

function resetRound() {
  attempts.value = 0
  failedAttempts.value = 0
  history.value = []
  elapsed.value = 0
  lockoutRemaining.value = 0
  draft.value = ''
  errorText.value = ''
  showHint.value = false
  errorFlash.value = false
  shaking.value = false
}

function resetGame() {
  resetRound()
  phase.value = 'setup'
  setupStep.value = 'enter'
  passcodeLength.value = 4
  passcode.value = ''
  firstPasscode.value = ''
  hintText.value = ''
  autoGenerated.value = false
  challenge.value = null
  shareToken.value = ''
  shareLink.value = ''
  shareState.value = 'idle'
  shareError.value = ''
  tokenError.value = ''
  clearChallengeInUrl()
}

/**
 * 进入挑战模式：只保留令牌，密码本身不进内存
 */
function enterChallenge(next: Challenge) {
  challenge.value = next
  passcodeLength.value = next.length
  passcode.value = ''
  hintText.value = ''
  resetRound()
  setupStep.value = 'enter'
  phase.value = 'locked'
}

/** 从 #/phone-lock?c=xxx 里读挑战码 */
function readChallengeFromUrl(): string | null {
  try {
    const hash = window.location.hash || ''
    const index = hash.indexOf('?')
    if (index === -1) return null
    return new URLSearchParams(hash.slice(index + 1)).get('c')
  } catch {
    return null
  }
}

function clearChallengeInUrl() {
  try {
    if (readChallengeFromUrl()) {
      window.history.replaceState(null, '', `${window.location.pathname}#/phone-lock`)
    }
  } catch {
    /* 忽略：地址栏清理失败不影响玩 */
  }
}

function acceptToken() {
  const token = tokenInput.value.trim()
  if (!token) return
  const parsed = parseChallenge(token)
  if (!parsed) {
    tokenError.value = '挑战码无法识别，可能被聊天软件截断了，让对方重新发一次'
    return
  }
  tokenError.value = ''
  tokenInput.value = ''
  enterChallenge(parsed)
}

/**
 * 生成分享链接：链接里只有令牌，没有密码
 */
async function generateShareLink() {
  if (!passcode.value || shareState.value === 'generating') return
  shareState.value = 'generating'
  shareError.value = ''
  try {
    const next = await createChallenge(passcode.value)
    const token = encodeChallenge(next)
    shareToken.value = token
    shareLink.value = `${window.location.origin}${window.location.pathname}#/phone-lock?c=${token}`
    shareState.value = 'ready'

    // 顺手实测一次本机校验耗时，用来估算对方离线穷举的成本
    const started = performance.now()
    await verifyChallenge(next, passcode.value)
    verifySeconds.value = (performance.now() - started) / 1000
  } catch (error) {
    shareState.value = 'idle'
    shareError.value = error instanceof Error ? error.message : '生成失败，请重试'
  }
}

async function copyText(text: string, tag: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text)
      copied.value = tag
      setTimeout(() => {
        if (copied.value === tag) copied.value = ''
      }, 2000)
      return true
    }
  } catch {
    /* 继续走下面的兜底 */
  }
  try {
    const area = document.createElement('textarea')
    area.value = text
    area.setAttribute('readonly', 'readonly')
    area.style.position = 'fixed'
    area.style.opacity = '0'
    document.body.appendChild(area)
    area.select()
    const ok = document.execCommand('copy')
    area.remove()
    copied.value = ok ? tag : ''
    return ok
  } catch {
    return false
  }
}

function selectShareInput(event: FocusEvent) {
  const target = event.target as HTMLInputElement | null
  target?.select()
}

const copyShareLink = () => copyText(shareLink.value, 'link')
const copyShareToken = () => copyText(shareToken.value, 'token')

async function submitGuess() {
  const guess = draft.value
  const active = challenge.value
  attempts.value++
  history.value = [guess, ...history.value].slice(0, 6)

  let correct = false
  if (active) {
    // 挑战模式：本地根本没有密码，只能拿令牌现场跑一次 KDF
    verifying.value = true
    const started = performance.now()
    try {
      correct = await verifyChallenge(active, guess)
    } catch {
      correct = false
      errorText.value = '校验失败，请刷新页面重试'
    } finally {
      verifying.value = false
      verifySeconds.value = (performance.now() - started) / 1000
    }
  } else {
    correct = guess === passcode.value
  }

  if (correct) {
    draft.value = ''
    errorText.value = ''
    lockoutRemaining.value = 0
    phase.value = 'unlocked'
    return
  }

  failedAttempts.value++

  const lockout = getLockoutSeconds(failedAttempts.value)
  const remaining = getRemainingAttemptsBeforeLockout(failedAttempts.value)

  if (lockout > 0) {
    lockoutRemaining.value = lockout
    errorText.value = ''
  } else {
    errorText.value = `密码错误，还可尝试 ${remaining} 次`
  }

  flashError()
}

function flashError(message = '') {
  if (message) errorText.value = message
  errorFlash.value = true
  shaking.value = true

  if (shakeTimer) clearTimeout(shakeTimer)
  shakeTimer = setTimeout(() => {
    shaking.value = false
  }, 500)

  // 抖动结束后再清空输入的密码点
  if (clearTimer) clearTimeout(clearTimer)
  clearTimer = setTimeout(() => {
    errorFlash.value = false
    draft.value = ''
  }, 600)
}

function tick() {
  now.value = new Date()

  if (phase.value === 'locked') {
    elapsed.value++
  }

  if (lockoutRemaining.value > 0) {
    lockoutRemaining.value--
  }
}

function handleKeydown(event: KeyboardEvent) {
  const target = event.target as HTMLElement | null
  if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA')) return

  if (/^\d$/.test(event.key)) {
    handleDigit(event.key)
  } else if (event.key === 'Backspace') {
    handleDelete()
  } else if (event.key === 'Escape') {
    showHint.value = false
  }
}

function handleHashChange() {
  const token = readChallengeFromUrl()
  const parsed = parseChallenge(token)
  if (parsed && encodeChallenge(parsed) !== (challenge.value && encodeChallenge(challenge.value))) {
    enterChallenge(parsed)
  }
}

onMounted(() => {
  tickTimer = setInterval(tick, 1000)
  window.addEventListener('keydown', handleKeydown)
  window.addEventListener('hashchange', handleHashChange)

  const parsed = parseChallenge(readChallengeFromUrl())
  if (parsed) enterChallenge(parsed)
})

onUnmounted(() => {
  if (tickTimer) clearInterval(tickTimer)
  if (shakeTimer) clearTimeout(shakeTimer)
  if (clearTimer) clearTimeout(clearTimer)
  window.removeEventListener('keydown', handleKeydown)
  window.removeEventListener('hashchange', handleHashChange)
})
</script>

<style scoped>
/* ============================================================
   页面背景：柔和渐变 + 毛玻璃光斑
   ============================================================ */
.phone-lock-view {
  position: relative;
  height: calc(100vh - 60px);
  height: calc(100dvh - 60px);
  padding: 18px 20px 28px;
  overscroll-behavior: contain;
  -webkit-overflow-scrolling: touch;
  /* 手机内部所有尺寸都跟着它缩放，兼容移动端浏览器地址栏变化 */
  --hunit: 1vh;
  background:
    radial-gradient(120vmax 70vmax at 6% -12%, #e4eaff 0%, transparent 55%),
    radial-gradient(100vmax 60vmax at 104% 4%, #ffe7f3 0%, transparent 52%),
    linear-gradient(165deg, #f4f6ff 0%, #f8fbff 46%, #eef3ff 100%);
}

@supports (height: 100dvh) {
  .phone-lock-view {
    --hunit: 1dvh;
  }
}

.aurora {
  position: absolute;
  inset: 0;
  z-index: 0;
  overflow: hidden;
  pointer-events: none;
}

.blob {
  position: absolute;
  display: block;
  border-radius: 50%;
  filter: blur(64px);
  opacity: 0.5;
  will-change: transform;
}

.blob-1 {
  width: 46vmin;
  height: 46vmin;
  top: -12vmin;
  left: -8vmin;
  background: #8ea2ff;
  animation: blob-drift 22s ease-in-out infinite;
}

.blob-2 {
  width: 38vmin;
  height: 38vmin;
  top: -4vmin;
  right: -6vmin;
  background: #ff9ecb;
  animation: blob-drift 26s ease-in-out infinite reverse;
}

.blob-3 {
  width: 42vmin;
  height: 42vmin;
  bottom: -16vmin;
  left: 16vmin;
  background: #7fd8ff;
  animation: blob-drift 30s ease-in-out infinite;
}

.blob-4 {
  width: 30vmin;
  height: 30vmin;
  right: 4vmin;
  bottom: -10vmin;
  background: #c4b5fd;
  animation: blob-drift 24s ease-in-out infinite reverse;
}

@keyframes blob-drift {
  0%,
  100% {
    transform: translate3d(0, 0, 0) scale(1);
  }
  50% {
    transform: translate3d(3vmin, -2.5vmin, 0) scale(1.1);
  }
}

.stage {
  position: relative;
  z-index: 1;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: flex-start;
  gap: 32px;
  max-width: 940px;
  margin: 0 auto;
  padding-bottom: 12px;
}

/* ============================================================
   手机外观
   ============================================================ */
.phone-frame {
  position: relative;
  flex: 0 0 auto;
  width: min(342px, 92vw);
  height: min(704px, calc(100vh - 152px));
  height: min(704px, calc(100dvh - 152px));
  min-height: min(540px, max(470px, calc(100vh - 130px)));
  min-height: min(540px, max(470px, calc(100dvh - 130px)));
  padding: 8px;
  border-radius: 54px;
  background:
    linear-gradient(150deg, #f4f5f7 0%, #c3c8d0 14%, #eef0f3 30%, #9aa1ab 50%, #dfe3e8 68%, #a7aeb8 86%, #cdd2d9 100%);
  box-shadow:
    0 48px 80px -30px rgba(30, 41, 120, 0.5),
    0 14px 30px -12px rgba(15, 23, 42, 0.22),
    inset 0 0 0 1px rgba(255, 255, 255, 0.7),
    inset 0 -2px 6px rgba(15, 23, 42, 0.25);
}

/* 屏幕四周的黑色边框，让机身更像真机 */
.phone-bezel {
  position: relative;
  width: 100%;
  height: 100%;
  padding: 4px;
  border-radius: 47px;
  background: linear-gradient(180deg, #0a0c11, #04060a);
  box-shadow:
    inset 0 0 0 1px rgba(255, 255, 255, 0.12),
    inset 0 3px 10px rgba(0, 0, 0, 0.9),
    0 1px 0 rgba(255, 255, 255, 0.35);
}

.side-btn {
  position: absolute;
  background: linear-gradient(180deg, #b9bfc7, #7c838d);
  border-radius: 2px;
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.6);
}

.side-silent {
  left: -2px;
  top: 104px;
  width: 3px;
  height: 26px;
}

.side-vol-up {
  left: -2px;
  top: 150px;
  width: 3px;
  height: 52px;
}

.side-vol-down {
  left: -2px;
  top: 214px;
  width: 3px;
  height: 52px;
}

.side-power {
  right: -2px;
  top: 182px;
  width: 3px;
  height: 84px;
}

.phone-screen {
  position: relative;
  width: 100%;
  height: 100%;
  border-radius: 43px;
  overflow: hidden;
  background: #04060a;
  display: flex;
  flex-direction: column;
  font-family: -apple-system, 'SF Pro Display', 'Helvetica Neue', 'PingFang SC', Arial, sans-serif;
  -webkit-user-select: none;
  user-select: none;
  -webkit-tap-highlight-color: transparent;
  touch-action: manipulation;
}

.screen-glare {
  position: absolute;
  inset: 0;
  z-index: 9;
  pointer-events: none;
  background:
    linear-gradient(118deg, rgba(255, 255, 255, 0.18) 0%, rgba(255, 255, 255, 0.04) 24%, transparent 44%),
    radial-gradient(120% 55% at 50% -8%, rgba(255, 255, 255, 0.14), transparent 62%);
}

/* 输错时只在顶部透出一点点红光，不闪烁 */
.error-glow {
  position: absolute;
  inset: 0;
  z-index: 8;
  pointer-events: none;
  opacity: 0;
  background: radial-gradient(130% 60% at 50% 0%, rgba(255, 96, 86, 0.28), transparent 62%);
  transition: opacity 0.55s ease;
}

.error-glow.is-on {
  opacity: 1;
  transition-duration: 0.14s;
}

.wallpaper {
  position: absolute;
  inset: 0;
  transition: filter 0.4s ease;
}

.wallpaper::after {
  content: '';
  position: absolute;
  inset: 0;
  background: radial-gradient(125% 75% at 50% 0%, transparent 42%, rgba(0, 0, 0, 0.42) 100%);
}

.wp-aurora {
  background:
    radial-gradient(58% 42% at 16% 6%, rgba(126, 226, 255, 0.6), transparent 62%),
    radial-gradient(52% 38% at 88% 16%, rgba(178, 126, 255, 0.55), transparent 64%),
    radial-gradient(72% 50% at 46% 102%, rgba(255, 118, 190, 0.42), transparent 66%),
    linear-gradient(168deg, #070c26 0%, #232a72 42%, #59389b 72%, #b4518f 100%);
}

.wp-sunset {
  background:
    radial-gradient(60% 42% at 82% 6%, rgba(255, 214, 122, 0.7), transparent 62%),
    radial-gradient(58% 44% at 12% 18%, rgba(255, 118, 118, 0.5), transparent 64%),
    radial-gradient(76% 52% at 50% 104%, rgba(46, 12, 60, 0.92), transparent 68%),
    linear-gradient(170deg, #2a1038 0%, #7f3465 40%, #d0615c 72%, #f0a95c 100%);
}

.wp-neon {
  background:
    radial-gradient(58% 42% at 22% 10%, rgba(255, 74, 176, 0.55), transparent 62%),
    radial-gradient(54% 40% at 84% 22%, rgba(64, 196, 255, 0.5), transparent 64%),
    radial-gradient(74% 52% at 50% 104%, rgba(10, 6, 40, 0.95), transparent 68%),
    linear-gradient(165deg, #12002c 0%, #430c66 44%, #96156f 74%, #2a63c9 100%);
}

.wp-midnight {
  background:
    radial-gradient(56% 40% at 20% 8%, rgba(72, 132, 214, 0.42), transparent 62%),
    radial-gradient(50% 38% at 86% 24%, rgba(96, 78, 206, 0.38), transparent 64%),
    radial-gradient(72% 50% at 50% 104%, rgba(16, 78, 104, 0.55), transparent 68%),
    linear-gradient(170deg, #04060d 0%, #0c1528 46%, #16233d 74%, #1f4a63 100%);
}

/* 桌面：同一张墙纸压暗一点，图标更清楚 */
.wallpaper-home {
  filter: brightness(0.86) saturate(1.06);
}

.dynamic-island {
  position: absolute;
  top: 8px;
  left: 50%;
  transform: translateX(-50%);
  width: 96px;
  height: 26px;
  border-radius: 15px;
  background: #000;
  z-index: 6;
  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.06);
}

.dynamic-island::after {
  content: '';
  position: absolute;
  top: 50%;
  right: 8px;
  width: 9px;
  height: 9px;
  border-radius: 50%;
  transform: translateY(-50%);
  background: radial-gradient(circle at 34% 32%, #2c3c5c, #04060c 70%);
  box-shadow: inset 0 0 3px rgba(130, 190, 255, 0.45);
}

.status-bar {
  position: relative;
  z-index: 5;
  height: 46px;
  padding: 0 26px 0 30px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  color: #fff;
  font-size: 13px;
  font-weight: 600;
  text-shadow: 0 1px 6px rgba(0, 0, 0, 0.25);
}

.status-icons {
  display: flex;
  align-items: center;
  gap: 5px;
}

.status-icon {
  width: 16px;
  height: 12px;
  display: block;
}

.status-battery {
  width: 24px;
}

.screen-body {
  position: relative;
  z-index: 4;
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  padding: 0 18px 14px;
  animation: screen-in 0.42s cubic-bezier(0.22, 1, 0.36, 1) both;
}

@keyframes screen-in {
  from {
    opacity: 0;
    transform: scale(0.97) translateY(8px);
  }
  to {
    opacity: 1;
    transform: none;
  }
}

/* ============================================================
   密码点
   ============================================================ */
.dots {
  display: flex;
  justify-content: center;
  gap: clamp(11px, calc(var(--hunit) * 1.9), 16px);
  margin: clamp(9px, calc(var(--hunit) * 1.6), 14px) 0 6px;
}

.dot {
  width: clamp(10px, calc(var(--hunit) * 1.6), 13px);
  height: clamp(10px, calc(var(--hunit) * 1.6), 13px);
  border-radius: 50%;
  border: 1.5px solid rgba(255, 255, 255, 0.85);
  transition: background 0.15s, border-color 0.2s, box-shadow 0.2s, transform 0.15s;
}

.dot.is-filled {
  background: #fff;
  transform: scale(1.06);
  box-shadow: 0 0 10px rgba(255, 255, 255, 0.6);
}

.dots.is-error .dot {
  border-color: #ff8a80;
}

.dots.is-error .dot.is-filled {
  background: #ff8a80;
  box-shadow: 0 0 10px rgba(255, 138, 128, 0.55);
}

/* 输错时只让密码点轻轻晃两下，整机不动 */
.dots.is-shaking {
  animation: dots-shake 0.34s ease-out;
}

@keyframes dots-shake {
  0%,
  100% {
    transform: translateX(0);
  }
  22% {
    transform: translateX(-3px);
  }
  46% {
    transform: translateX(2.5px);
  }
  70% {
    transform: translateX(-1.5px);
  }
  88% {
    transform: translateX(1px);
  }
}

/* 屏幕内统一的毛玻璃容器 */
.keypad-panel {
  margin-top: auto;
  padding: clamp(8px, calc(var(--hunit) * 1.6), 14px) clamp(6px, 2vw, 10px);
  border-radius: 30px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.035));
  border: 1px solid rgba(255, 255, 255, 0.13);
  box-shadow: 0 14px 30px -12px rgba(4, 6, 20, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.18);
  -webkit-backdrop-filter: blur(22px) saturate(160%);
  backdrop-filter: blur(22px) saturate(160%);
}

.lock-badge {
  font-size: 18px;
  text-align: center;
  line-height: 1;
}

/* ============================================================
   1. 设置密码
   ============================================================ */
.setup-head {
  margin-top: 10px;
  padding: 20px 16px 16px;
  border-radius: 26px;
  text-align: center;
  color: #fff;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0.05));
  border: 1px solid rgba(255, 255, 255, 0.18);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3);
  -webkit-backdrop-filter: blur(18px) saturate(160%);
  backdrop-filter: blur(18px) saturate(160%);
}

.setup-title {
  margin: 10px 0 4px;
  font-size: 19px;
  font-weight: 600;
  letter-spacing: 0.5px;
}

.setup-tip {
  margin: 0;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.75);
}

.setup-error {
  margin: 6px 0 0;
  font-size: 12px;
  color: #ff8b83;
}

.segmented {
  display: inline-flex;
  margin-top: 14px;
  padding: 4px;
  border-radius: 12px;
  background: rgba(255, 255, 255, 0.14);
  border: 1px solid rgba(255, 255, 255, 0.2);
  -webkit-backdrop-filter: blur(12px);
  backdrop-filter: blur(12px);
}

.segmented button {
  border: none;
  background: transparent;
  color: rgba(255, 255, 255, 0.78);
  font-size: 12px;
  padding: 7px 15px;
  border-radius: 9px;
  cursor: pointer;
  touch-action: manipulation;
  transition: background 0.2s, color 0.2s, box-shadow 0.2s;
}

.segmented button.is-active {
  background: rgba(255, 255, 255, 0.92);
  color: #1f2937;
  font-weight: 600;
  box-shadow: 0 3px 10px rgba(0, 0, 0, 0.2);
}

.hint-step {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  margin-top: 10px;
  padding: 24px 18px;
  border-radius: 26px;
  color: #fff;
  text-align: center;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0.05));
  border: 1px solid rgba(255, 255, 255, 0.18);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3);
  -webkit-backdrop-filter: blur(18px) saturate(160%);
  backdrop-filter: blur(18px) saturate(160%);
}

.hint-title {
  margin: 0;
  font-size: 18px;
}

.hint-sub {
  margin: 0;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.7);
}

.hint-input {
  width: 100%;
  margin-top: 6px;
  padding: 12px 14px;
  border-radius: 14px;
  border: 1px solid rgba(255, 255, 255, 0.32);
  background: rgba(255, 255, 255, 0.16);
  color: #fff;
  font-size: 14px;
  outline: none;
  -webkit-user-select: text;
  user-select: text;
  -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
  transition: border-color 0.2s, box-shadow 0.2s, background 0.2s;
}

.hint-input::placeholder {
  color: rgba(255, 255, 255, 0.55);
}

.hint-input:focus {
  border-color: rgba(255, 255, 255, 0.85);
  background: rgba(255, 255, 255, 0.22);
  box-shadow: 0 0 0 4px rgba(255, 255, 255, 0.12);
}

.random-tip {
  margin: 0;
  font-size: 12px;
  color: #fde68a;
}

/* ============================================================
   通用按钮
   ============================================================ */
.primary-btn {
  margin-top: 8px;
  padding: 12px 28px;
  border: 1px solid rgba(255, 255, 255, 0.7);
  border-radius: 999px;
  background: linear-gradient(180deg, #ffffff, #eef1f8);
  color: #1f2937;
  font-size: 15px;
  font-weight: 600;
  cursor: pointer;
  touch-action: manipulation;
  box-shadow: 0 10px 24px rgba(8, 10, 30, 0.28), inset 0 1px 0 #fff;
  transition: transform 0.16s ease, box-shadow 0.16s ease;
}

.primary-btn:hover {
  transform: translateY(-1px);
  box-shadow: 0 14px 30px rgba(8, 10, 30, 0.32), inset 0 1px 0 #fff;
}

.primary-btn:active {
  transform: scale(0.97);
}

.link-btn {
  background: transparent;
  border: none;
  color: rgba(255, 255, 255, 0.82);
  font-size: 12px;
  text-decoration: underline;
  text-underline-offset: 3px;
  cursor: pointer;
  padding: 6px 10px;
  touch-action: manipulation;
  transition: color 0.2s;
}

.link-btn:hover {
  color: #fff;
}

/* ============================================================
   2. 交接
   ============================================================ */
.handoff-screen {
  align-items: center;
  justify-content: center;
  gap: 8px;
  margin-top: 10px;
  padding: 26px 18px;
  border-radius: 26px;
  text-align: center;
  color: #fff;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.15), rgba(255, 255, 255, 0.05));
  border: 1px solid rgba(255, 255, 255, 0.18);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3);
  -webkit-backdrop-filter: blur(18px) saturate(160%);
  backdrop-filter: blur(18px) saturate(160%);
}

.handoff-icon {
  font-size: 46px;
  filter: drop-shadow(0 8px 18px rgba(0, 0, 0, 0.35));
}

.handoff-title {
  margin: 6px 0 0;
  font-size: 20px;
}

.handoff-text {
  margin: 0 0 8px;
  font-size: 13px;
  line-height: 1.7;
  color: rgba(255, 255, 255, 0.8);
}

.handoff-hint {
  max-width: 100%;
  margin-bottom: 8px;
  padding: 9px 15px;
  border-radius: 14px;
  font-size: 13px;
  word-break: break-all;
  background: rgba(255, 255, 255, 0.18);
  border: 1px solid rgba(255, 255, 255, 0.24);
  -webkit-backdrop-filter: blur(10px);
  backdrop-filter: blur(10px);
}

/* ============================================================
   3. 锁屏
   ============================================================ */
.lock-screen {
  padding-bottom: 10px;
}

.lock-clock {
  flex: 1;
  min-height: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6px;
  color: #fff;
}

.clock-widget {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: clamp(3px, calc(var(--hunit) * 0.7), 5px) 12px;
  border-radius: 999px;
  font-size: clamp(11px, calc(var(--hunit) * 1.6), 13px);
  color: rgba(255, 255, 255, 0.94);
  background: rgba(255, 255, 255, 0.14);
  border: 1px solid rgba(255, 255, 255, 0.2);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.26);
  -webkit-backdrop-filter: blur(14px) saturate(150%);
  backdrop-filter: blur(14px) saturate(150%);
}

.clock-widget .lock-badge {
  font-size: 12px;
}

.clock-date {
  opacity: 0.95;
}

.clock-time {
  font-size: clamp(34px, calc(var(--hunit) * 9.3), 76px);
  font-weight: 500;
  line-height: 1;
  letter-spacing: -3px;
  font-variant-numeric: tabular-nums;
  text-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
}

.lock-prompt {
  min-height: clamp(54px, calc(var(--hunit) * 10), 84px);
  text-align: center;
  color: #fff;
}

.prompt-text {
  margin: 0;
  min-height: 20px;
  font-size: 14px;
  text-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
}

.prompt-sub {
  margin: 4px 0 0;
  font-size: 12px;
  color: rgba(255, 255, 255, 0.85);
}

.prompt-lockout {
  color: #fecaca;
}

/* ============================================================
   4. 解锁后的桌面
   ============================================================ */
.home-screen {
  padding-top: 4px;
}

.unlock-badge {
  align-self: center;
  margin: 4px 0 16px;
  padding: 7px 15px;
  border-radius: 999px;
  font-size: 11px;
  text-align: center;
  color: #fff;
  background: rgba(255, 255, 255, 0.22);
  border: 1px solid rgba(255, 255, 255, 0.3);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.35);
  -webkit-backdrop-filter: blur(12px) saturate(160%);
  backdrop-filter: blur(12px) saturate(160%);
}

.app-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px 8px;
}

.app {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  animation: app-pop 0.5s cubic-bezier(0.22, 1, 0.36, 1) both;
}

.app-grid .app:nth-child(1) { animation-delay: 0.04s; }
.app-grid .app:nth-child(2) { animation-delay: 0.08s; }
.app-grid .app:nth-child(3) { animation-delay: 0.12s; }
.app-grid .app:nth-child(4) { animation-delay: 0.16s; }
.app-grid .app:nth-child(5) { animation-delay: 0.2s; }
.app-grid .app:nth-child(6) { animation-delay: 0.24s; }
.app-grid .app:nth-child(7) { animation-delay: 0.28s; }
.app-grid .app:nth-child(8) { animation-delay: 0.32s; }

@keyframes app-pop {
  from {
    opacity: 0;
    transform: scale(0.7);
  }
  to {
    opacity: 1;
    transform: none;
  }
}

.app-icon {
  width: 52px;
  height: 52px;
  border-radius: 15px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 26px;
  box-shadow: 0 6px 14px rgba(0, 0, 0, 0.28), inset 0 1px 0 rgba(255, 255, 255, 0.45);
}

.app-name {
  font-size: 10px;
  color: #fff;
  text-shadow: 0 1px 3px rgba(0, 0, 0, 0.5);
}

.dock {
  margin-top: auto;
  margin-bottom: 6px;
  padding: 12px 10px;
  border-radius: 26px;
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
  background: rgba(255, 255, 255, 0.18);
  border: 1px solid rgba(255, 255, 255, 0.22);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.3);
  -webkit-backdrop-filter: blur(18px) saturate(160%);
  backdrop-filter: blur(18px) saturate(160%);
}

.dock .app {
  animation: none;
}

.home-indicator {
  position: absolute;
  bottom: 7px;
  left: 50%;
  transform: translateX(-50%);
  width: 118px;
  height: 5px;
  border-radius: 3px;
  background: rgba(255, 255, 255, 0.78);
  z-index: 7;
}

/* ============================================================
   侧边信息面板（毛玻璃卡片）
   ============================================================ */
.info-panel {
  flex: 1 1 320px;
  min-width: 0;
  max-width: 430px;
  padding: 24px;
  border-radius: 24px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.74), rgba(255, 255, 255, 0.5));
  border: 1px solid rgba(255, 255, 255, 0.75);
  box-shadow: 0 28px 64px -28px rgba(30, 41, 120, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.9);
  -webkit-backdrop-filter: blur(26px) saturate(180%);
  backdrop-filter: blur(26px) saturate(180%);
}

.panel-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  margin-bottom: 6px;
}

.panel-title {
  margin: 0;
  font-size: 19px;
  font-weight: 700;
  color: #232838;
  letter-spacing: 0.2px;
}

.phase-chip {
  flex: 0 0 auto;
  padding: 5px 11px;
  border-radius: 999px;
  font-size: 11px;
  font-weight: 600;
  white-space: nowrap;
  border: 1px solid transparent;
}

.phase-chip.is-setup {
  color: #5b53c9;
  background: #eeecff;
  border-color: #ded9ff;
}

.phase-chip.is-wait {
  color: #b07a1e;
  background: #fdf3e2;
  border-color: #f7e3bd;
}

.phase-chip.is-run {
  color: #2b6cd4;
  background: #e9f1ff;
  border-color: #d1e1ff;
}

.phase-chip.is-done {
  color: #1f8a5b;
  background: #e6f8ef;
  border-color: #c7eedd;
}

.phase-chip.is-danger {
  color: #c0392b;
  background: #fdecea;
  border-color: #f8d4cf;
}

.phase-chip.is-challenge {
  color: #a2451f;
  background: #fdeee4;
  border-color: #f7d6c2;
}

.panel-desc {
  margin: 0 0 16px;
  font-size: 12.5px;
  line-height: 1.65;
  color: #7b8290;
}

.rule-list {
  counter-reset: rule;
  list-style: none;
  display: grid;
  gap: 9px;
  margin: 0 0 16px;
  padding: 0;
}

.rule-list li {
  position: relative;
  counter-increment: rule;
  padding-left: 26px;
  font-size: 12.5px;
  line-height: 1.6;
  color: #596070;
}

.rule-list li::before {
  content: counter(rule);
  position: absolute;
  left: 0;
  top: 1px;
  width: 18px;
  height: 18px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  font-weight: 700;
  color: #fff;
  background: linear-gradient(140deg, #7f9dff, #a97dff);
  box-shadow: 0 3px 8px -3px rgba(97, 106, 255, 0.9);
}

.wallpaper-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 10px 14px;
  border-radius: 16px;
  margin-bottom: 14px;
  background: rgba(255, 255, 255, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.85);
  box-shadow: 0 4px 14px -8px rgba(30, 41, 120, 0.5);
}

.wallpaper-label {
  font-size: 12.5px;
  font-weight: 600;
  color: #4b5162;
}

.swatches {
  display: flex;
  gap: 9px;
}

.swatch {
  width: 26px;
  height: 26px;
  padding: 0;
  border: 2px solid #fff;
  border-radius: 50%;
  cursor: pointer;
  touch-action: manipulation;
  box-shadow: 0 0 0 1px rgba(15, 23, 42, 0.08), 0 5px 12px -6px rgba(15, 23, 42, 0.6);
  transition: transform 0.18s ease, box-shadow 0.18s ease;
}

.swatch:hover {
  transform: scale(1.08);
}

.swatch.is-active {
  transform: scale(1.1);
  box-shadow: 0 0 0 2px #6c7cff, 0 6px 14px -6px rgba(76, 88, 255, 0.9);
}

.panel-block {
  padding: 0;
}

.panel-hint {
  margin: 0;
  padding: 12px 14px;
  border-radius: 12px;
  font-size: 13px;
  color: #5b6270;
  background: rgba(255, 255, 255, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.8);
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
  margin-bottom: 16px;
}

.stat {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 3px;
  padding: 12px 4px;
  border-radius: 16px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.85), rgba(255, 255, 255, 0.6));
  border: 1px solid rgba(255, 255, 255, 0.9);
  box-shadow: 0 6px 16px -10px rgba(30, 41, 120, 0.7);
}

.stat-value {
  font-size: 18px;
  font-weight: 700;
  color: #232838;
  font-variant-numeric: tabular-nums;
  letter-spacing: -0.3px;
}

.stat-label {
  font-size: 10.5px;
  color: #8b93a1;
}

.history {
  margin-bottom: 14px;
}

.history-title {
  margin-bottom: 8px;
  font-size: 12px;
  color: #8b93a1;
}

.history-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  padding: 10px 13px;
  border-radius: 13px;
  margin-bottom: 6px;
  font-size: 12px;
  background: rgba(255, 255, 255, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.85);
  animation: app-pop 0.3s cubic-bezier(0.22, 1, 0.36, 1) both;
}

.history-guess {
  font-family: 'SF Mono', 'Monaco', 'Menlo', 'Courier New', monospace;
  font-size: 13px;
  letter-spacing: 3px;
  color: #2b3040;
}

.history-times {
  font-size: 11px;
  color: #98a0ad;
}

.hint-card {
  padding: 11px 14px;
  border-radius: 12px;
  margin-bottom: 14px;
  font-size: 12px;
  word-break: break-all;
  color: #b07a1e;
  background: linear-gradient(180deg, rgba(255, 244, 222, 0.9), rgba(255, 238, 205, 0.75));
  border: 1px solid rgba(255, 226, 173, 0.9);
}

.share-card,
.challenge-card {
  padding: 14px;
  border-radius: 18px;
  margin-bottom: 14px;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.86), rgba(255, 255, 255, 0.62));
  border: 1px solid rgba(255, 255, 255, 0.9);
  box-shadow: 0 10px 24px -16px rgba(30, 41, 120, 0.9);
}

.share-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 8px;
}

.share-title {
  font-size: 13px;
  font-weight: 700;
  color: #232838;
}

.share-badge {
  padding: 3px 9px;
  border-radius: 999px;
  font-size: 10px;
  font-weight: 600;
  color: #5b53c9;
  background: #eeecff;
  border: 1px solid #ded9ff;
}

.share-desc {
  margin: 0 0 10px;
  font-size: 11.5px;
  line-height: 1.65;
  color: #767e8c;
}

.share-input,
.challenge-input {
  width: 100%;
  padding: 9px 12px;
  border-radius: 12px;
  font-size: 11.5px;
  font-family: 'SF Mono', 'Monaco', 'Menlo', monospace;
  color: #3d4352;
  background: rgba(244, 246, 252, 0.9);
  border: 1px solid rgba(210, 216, 232, 0.9);
  box-sizing: border-box;
}

.share-input {
  margin-bottom: 10px;
  color: #5b6270;
}

.challenge-input {
  flex: 1;
  min-width: 0;
  font-size: 12px;
}

.share-input:focus,
.challenge-input:focus {
  outline: none;
  border-color: #9fb0ff;
  box-shadow: 0 0 0 3px rgba(124, 142, 255, 0.18);
}

.share-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.share-actions :deep(.el-button) {
  margin-left: 0;
}

.share-facts {
  list-style: none;
  display: grid;
  gap: 5px;
  margin: 10px 0 0;
  padding: 0;
  font-size: 11px;
  line-height: 1.6;
  color: #8b93a1;
}

.share-facts li {
  position: relative;
  padding-left: 12px;
}

.share-facts li::before {
  content: '·';
  position: absolute;
  left: 3px;
  color: #b6bcc9;
}

.share-facts li.is-warn {
  color: #b07a1e;
}

.share-facts li.is-muted {
  color: #a3aab8;
}

.share-facts li.is-warn::before {
  content: '';
}

.challenge-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.share-error {
  margin: 9px 0 0;
  font-size: 11.5px;
  line-height: 1.6;
  color: #c0392b;
}

.panel-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.panel-actions :deep(.el-button + .el-button) {
  margin-left: 0;
}

.panel-actions :deep(.el-button) {
  height: auto;
  padding: 11px 20px;
  border-radius: 999px;
  font-size: 13px;
  font-weight: 600;
  color: #414a5c;
  border: 1px solid rgba(255, 255, 255, 0.9);
  background: rgba(255, 255, 255, 0.8);
  box-shadow: 0 8px 18px -10px rgba(30, 41, 120, 0.8);
  transition: transform 0.16s ease, box-shadow 0.16s ease, background 0.16s ease;
}

.panel-actions :deep(.el-button:hover) {
  transform: translateY(-1px);
  background: #fff;
  border-color: #fff;
  color: #232838;
}

.panel-actions :deep(.el-button--primary) {
  color: #fff;
  border-color: transparent;
  background: linear-gradient(135deg, #5b7cfa, #8a63ff);
  box-shadow: 0 12px 24px -12px rgba(91, 124, 250, 0.95);
}

.panel-actions :deep(.el-button--primary:hover) {
  color: #fff;
  background: linear-gradient(135deg, #6484ff, #9469ff);
}

/* ============================================================
   浏览器不支持毛玻璃时的降级
   ============================================================ */
@supports not ((backdrop-filter: blur(4px)) or (-webkit-backdrop-filter: blur(4px))) {
  .info-panel {
    background: rgba(255, 255, 255, 0.95);
  }

  .keypad-panel,
  .setup-head,
  .hint-step,
  .handoff-screen {
    background: rgba(24, 22, 52, 0.58);
  }

  .clock-widget,
  .unlock-badge,
  .dock,
  .handoff-hint,
  .segmented {
    background: rgba(255, 255, 255, 0.24);
  }

  .stat,
  .history-item,
  .panel-hint,
  .share-card,
  .challenge-card {
    background: #fff;
  }
}

/* ============================================================
   响应式：平板 / 手机
   ============================================================ */
@media screen and (max-width: 900px) {
  .stage {
    gap: 22px;
  }

  .info-panel {
    flex: 1 1 100%;
    width: 100%;
    max-width: 460px;
  }
}

@media screen and (max-width: 768px) {
  /* 手机关掉自己的滚动条，交给外层滚动容器，避免嵌套滚动/卡顿 */
  .phone-lock-view {
    height: auto;
    min-height: calc(100vh - 60px);
    min-height: calc(100dvh - 60px);
    overflow: visible;
    padding: 12px 12px calc(18px + env(safe-area-inset-bottom, 0px));
  }

  .stage {
    gap: 18px;
    padding-bottom: 8px;
  }

  .phone-frame {
    width: min(360px, 100%);
    height: min(660px, calc(100vh - 120px));
    height: min(660px, calc(100dvh - 120px));
    min-height: min(560px, max(470px, calc(100vh - 110px)));
    min-height: min(560px, max(470px, calc(100dvh - 110px)));
    padding: 9px;
    border-radius: 48px;
    box-shadow:
      0 26px 56px -22px rgba(49, 46, 129, 0.42),
      0 8px 22px rgba(15, 23, 42, 0.14),
      inset 0 0 0 1px rgba(255, 255, 255, 0.5);
  }

  .phone-screen {
    border-radius: 40px;
  }

  .dynamic-island {
    width: 88px;
    height: 24px;
  }

  .screen-body {
    padding: 0 14px 12px;
  }

  .status-bar {
    height: 42px;
    padding: 0 22px 0 26px;
  }

  .setup-head,
  .hint-step,
  .handoff-screen {
    padding: 18px 14px;
    border-radius: 22px;
  }

  .info-panel {
    padding: 18px;
    border-radius: 20px;
  }

  .rule-list {
    font-size: 12.5px;
    line-height: 1.85;
  }

  /* iOS 上字号小于 16px 的输入框会自动放大页面 */
  .hint-input {
    font-size: 16px;
  }

  .blob {
    filter: blur(52px);
    opacity: 0.45;
  }
}

@media screen and (max-width: 400px) {
  .clock-time {
    letter-spacing: -2px;
  }

  .keypad-panel {
    border-radius: 26px;
  }

  .stats-grid {
    gap: 8px;
  }

  .stat-value {
    font-size: 15px;
  }

  .panel-actions {
    width: 100%;
  }

  .panel-actions :deep(.el-button) {
    flex: 1 1 auto;
  }

  .history-item {
    font-size: 11px;
  }
}

@media (max-height: 720px) {
  .blob {
    opacity: 0.38;
  }
}

/* 横屏小高度：压缩手机高度，避免溢出 */
@media (max-height: 560px) and (orientation: landscape) {
  .phone-frame {
    height: min(520px, calc(100vh - 120px));
    min-height: 470px;
  }

  .info-panel {
    max-width: 100%;
  }
}

/* ============================================================
   无障碍：尊重系统的「减少动态效果」
   ============================================================ */
@media (prefers-reduced-motion: reduce) {
  .blob,
  .screen-body,
  .app,
  .history-item,
  .dots.is-shaking {
    animation: none !important;
  }

  .primary-btn,
  .dot {
    transition: none;
  }
}
</style>
